A tiny bike sentry: Animation Class Reference
Animation Class Reference
Animation class that provides functions for various animations (e.g.
#include <Animation.h>
Public Member Functions
Animation ()
Constructor for Animation class.
void enter_sentry ()
Animation to play when enterying sentry state.
void enter_deep_sleep ()
Animation to play when enterying deep sleep state.
void in_sentry ()
Animation to play when in sentry mode.
void in_attention ()
Animation to play when in attention mode.
void exit_alarm ()
Animation to play when exiting alarm mode.
void in_alarm ()
Animation to play when in alarm mode.
Private Attributes
Timing timing
Timing instance.
Gpio gpio
GPIO instance.
bool led_state
current led state in alarm
Detailed Description
Animation class that provides functions for various animations (e.g.
when switching states)
Definition at line 20 of file Animation.h.
Constructor & Destructor Documentation
Animation()
Animation::Animation ()
Constructor for Animation class.
Definition at line 21 of file Animation.cpp.
References gpio, led_state, and Gpio::setup().
Member Function Documentation
enter_deep_sleep()
void Animation::enter_deep_sleep ()
Animation to play when enterying deep sleep state.
Definition at line 38 of file Animation.cpp.
References gpio, PIN_LED, and Gpio::toggle().
enter_sentry()
void Animation::enter_sentry ()
Animation to play when enterying sentry state.
Definition at line 30 of file Animation.cpp.
References gpio, PIN_LED, and Gpio::toggle().
exit_alarm()
void Animation::exit_alarm ()
Animation to play when exiting alarm mode.
Definition at line 62 of file Animation.cpp.
References gpio, Gpio::off(), PIN_BUZZER, and PIN_LED.
in_alarm()
void Animation::in_alarm ()
Animation to play when in alarm mode.
Definition at line 71 of file Animation.cpp.
References gpio, led_state, PIN_BUZZER, PIN_LED, and Gpio::set_pin().
in_attention()
void Animation::in_attention ()
Animation to play when in attention mode.
Definition at line 54 of file Animation.cpp.
References gpio, Gpio::on(), and PIN_LED.
in_sentry()
void Animation::in_sentry ()
Animation to play when in sentry mode.
Definition at line 46 of file Animation.cpp.
References gpio, Gpio::off(), and PIN_LED.
Field Documentation
gpio
Gpio Animation::gpio private
GPIO instance.
Definition at line 32 of file Animation.h.
Referenced by Animation(), enter_deep_sleep(), enter_sentry(), exit_alarm(), in_alarm(), in_attention(), and in_sentry().
led_state
bool Animation::led_state private
current led state in alarm
Definition at line 33 of file Animation.h.
Referenced by Animation(), and in_alarm().
timing
Timing Animation::timing private
Timing instance.
Definition at line 31 of file Animation.h.
The documentation for this class was generated from the following files:
src/main/Animation.h
src/main/Animation.cpp