ATtiny bike sentry: Gpio Class Reference
Gpio Class Reference
Gpio class that provides functions for direct hardware actions (e.g.
#include <Gpio.h>
Public Member Functions
Gpio ()
Constructor for Timing class.
void setup ()
GPIO setup function.
void on (byte pin)
Turns on a pin.
void off (byte pin)
Turns off a pin.
void set_pin (byte pin, bool state)
Sets pin to state.
void toggle (byte pin, int iterations, long d)
Function to toggle a digital pin on and off.
Private Attributes
Timing timing
Timing instance.
Detailed Description
Gpio class that provides functions for direct hardware actions (e.g.
turning on/off digital pins)
Definition at line 19 of file Gpio.h.
Constructor & Destructor Documentation
Gpio()
Gpio::Gpio ()
Constructor for Timing class.
Definition at line 21 of file Gpio.cpp.
References PIN_BUZZER, and PIN_LED.
Member Function Documentation
off()
void Gpio::off (byte pin)
Turns off a pin.
Parameters
pin pin to turn off
Definition at line 50 of file Gpio.cpp.
Referenced by Animation::exit_alarm(), and Animation::in_sentry().
on()
void Gpio::on (byte pin)
Turns on a pin.
Parameters
pin pin to turn on
Definition at line 41 of file Gpio.cpp.
Referenced by Animation::in_attention().
set_pin()
void Gpio::set_pin (byte pin, bool state)
Sets pin to state.
Parameters
pin pin to set state
state state to set (true/false)
Definition at line 60 of file Gpio.cpp.
Referenced by Animation::in_alarm().
setup()
void Gpio::setup ()
GPIO setup function.
Sets all output pins as outputs.
Definition at line 31 of file Gpio.cpp.
References PIN_BUZZER, and PIN_LED.
Referenced by Animation::Animation().
toggle()
void Gpio::toggle (byte pin, int iterations, long d)
Function to toggle a digital pin on and off.
Parameters
pin Pin to toggle on and off
iterations How often should pin be toggled
d delay between of/off states (d = 1 / frequency)
Definition at line 71 of file Gpio.cpp.
References timing, and Timing::wait_ms().
Referenced by Animation::enter_deep_sleep(), and Animation::enter_sentry().
Field Documentation
timing
Timing Gpio::timing private
Timing instance.
Definition at line 29 of file Gpio.h.
Referenced by toggle().
The documentation for this class was generated from the following files:
src/main/Gpio.h
src/main/Gpio.cpp